sudo: false

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install

language: node_js
node_js:
  - 9

branches:
  only:
    - master

deploy:
  provider: heroku
  api_key:
    secure: 0d0fe729-854c-415d-b74b-3a0980f52b5e
  app: test-ci-cd-travis-heroku-
  on:
    repo: dobernike/test-ci-cd-travis-heroku-
