sudo: false

language: node_js
node_js:
  - 12

branches:
  only:
    - master

deploy:
  provider: heroku
  api_key:
    secure: "ee67a78e-de39-436a-a7d5-121255cc0345"
  app: test-ci-cd-travis-heroku-
